spring.application.name=pedidos-api

#Springdoc OpenApi
springdoc.swagger-ui.path=/api-docs.html
springdoc.api-docs.path=/api-docs
springdoc.packages-to-scan=br.com.douglassouza.pedidos.api.controller

#Rabbitmq config
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#Rabbitmq custom configs
rabbitmq.exchange.name=pedidos.v1.pedido-criado