spring.application.name=notificacao


#Rabbitmq config
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#Reenvio de mensagens
spring.rabbitmq.listener.simple.default-requeue-rejected=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=4
spring.rabbitmq.listener.simple.retry.initial-interval=5s
spring.rabbitmq.listener.simple.retry.multiplier=2

rabbitmq.exchange.dlx.name=pedidos.v1.pedido-criado.dlx
rabbitmq.queue.dlq.name=pedidos.v1.pedido-criado.gerar-notificacao.dlq


#Rabbitmq custom configs
rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.queue.name=pedidos.v1.pedido-criado.gerar-notificacao

#spring mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

