spring.application.name=notificacao


#Rabbitmq config
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

#Rabbitmq custom configs
rabbitmq.exchange.name=pedidos.v1.pedido-criado
rabbitmq.queue.name=pedidos.v1.pedido-criado.gerar-notificacao

#spring mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

